### ISSUE TITLE
Hangs on blank screen

### ISSUE THREAD

**Issue by 0003c9fe** [prikhi/lightdm-mini-greeter#50] opened 2019-09-06 09:53 UTC
When I turn on my compter, once lightdm starts it simply hangs on a blank screen with a blinking underscore for about a minute, after which I can change tty and continue using the computer after logging in and using startx.

Here's the result of lightdm --test-mode -d

```
[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.30.0, UID=0 PID=1922
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Using Xephyr for X servers
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
[+0.00s] DEBUG: Monitoring logind for seats
[+0.01s] DEBUG: New seat added from logind: seat0
[+0.01s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.01s] DEBUG: Seat seat0: Starting
[+0.01s] DEBUG: Seat seat0: Creating greeter session
[+0.01s] DEBUG: Seat seat0: Creating display server of type x
[+0.01s] DEBUG: posix_spawn avoided (fd close requested) 
[+0.01s] DEBUG: Using VT 7
[+0.01s] DEBUG: Seat seat0: Starting local X display on VT 7
[+0.01s] DEBUG: XServer 1: Logging to /var/log/lightdm/x-1.log
[+0.01s] DEBUG: XServer 1: Writing X server authority to /run/lightdm/root/:1
[+0.01s] DEBUG: XServer 1: Launching X Server
[+0.01s] DEBUG: Launching process 1928: /usr/bin/Xephyr :1 -seat seat0 -auth /run/lightdm/root/:1 -nolisten tcp vt7 -novtswitch
[+0.01s] DEBUG: XServer 1: Waiting for ready signal from X server :1
[+0.01s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.01s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.01s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.01s] DEBUG: User /org/freedesktop/Accounts/User1000 added
[+0.02s] DEBUG: Process 1928 exited with return value 1
[+0.02s] DEBUG: XServer 1: X server stopped
[+0.02s] DEBUG: Releasing VT 7
[+0.02s] DEBUG: XServer 1: Removing X server authority /run/lightdm/root/:1
[+0.02s] DEBUG: Seat seat0: Display server stopped
[+0.02s] DEBUG: Seat seat0: Stopping session
[+0.02s] DEBUG: Seat seat0: Session stopped
[+0.02s] DEBUG: Seat seat0: Stopping display server, no sessions require it
[+0.02s] DEBUG: Seat seat0: Stopping; greeter display server failed to start
[+0.02s] DEBUG: Seat seat0: Stopping
[+0.02s] DEBUG: Seat seat0: Stopped
[+0.02s] DEBUG: Required seat has stopped
[+0.02s] DEBUG: Stopping display manager
[+0.02s] DEBUG: Display manager stopped
[+0.02s] DEBUG: Stopping daemon
[+0.02s] DEBUG: Exiting with return value 1
```

**Comment by JackWoodside** [comment] 2019-09-07 02:18
Hmm, it seems like this was happening because the font name I'd used in the config file wasn't valid. Is it possible for invalid config options to return to a default option to prevent this?

**Comment by prikhi** [comment] 2020-04-03 09:59
Do you remember what you had put for the `font` option? Did it need to be surrounded in quotes or something?

**Comment by 0003c9fe** [comment] 2020-04-03 10:44
I had quotes already, just mistyped the font (I think I missed a hyphen or something).

**Comment by prikhi** [comment] 2020-04-06 13:32
Hmm, when I enter an invalid font, the greeter still loads up for me, just with what I assume is GTKs default font.

I know it's been a while since you opened this, but if you can come up w/ a config to reproduce this, I might be able to fix it. Otherwise, I'm not sure where to poke around :man_shrugging:

**Comment by 0003c9fe** [comment] 2020-04-06 13:44
Actually thinking back, I'm not sure what it was, as it later turned out I still had the font wrong, and was using the default font for a while. Perhaps I missed a quote or something, but it was a long time ago, and my lightdm configs aren't in my dotfiles so I don't have any record of them, so I'm not sure I'd be able to reproduce it.

**Comment by prikhi** [comment] 2020-04-06 13:54
Alrighty, I'm just gonna close this out then if that sounds good to you.

**Closed by prikhi** 2020-04-06 13:54 UTC
Labels: bug
